language: java
os:
  - linux
stages:
  - prepare
  - build
  - release
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/releases
jobs:
  include:
    - stage: "prepare"
      name: "Prepare"
      script: >
           git config --local user.name 'Thomas Herzog'
           && git config --local user.email 'thomas.herzog@gepardec.com'
           && mkdir -p $HOME/releases

    - stage: "build"
      name: "Build"
      addons:
        apt:
          packages:
            - graphviz
      script: >
           mvn -f ./slides/pom.xml clean install
           && find ./slides/all/target -regextype posix-extended -regex '.*git.*' -execdir cp {} $HOME/releases/{} \;

    - stage: "release"
      name: "Release"
      script: skip
      deploy:
        provider: releases
        overwrite: true
        file_glob: true
        skip_cleanup: true
        api_key: "${GITHUB_OAUTH_TOKEN}"
        file: "$HOME/releases/*"
        on:
          tags: true
