language: java
os:
  - linux
cache:
  directories:
    - $HOME/.m2/repository
stages:
  - prepare
  - build
  - release
jobs:
  include:
    - stage: "prepare"
      name: "Prepare"
      script: >
           git config --local user.name 'Thomas Herzog'
           && git config --local user.email 'thomas.herzog@gepardec.com'
    - stage: "build"
      name: "Build"
      addons:
        apt:
          packages:
            - graphviz
      script: mvn -f ./slides/pom.xml clean install
    - stage: "release"
      name: "Release"
      script: skip
      before_deploy:
        - ls ${TRAVIS_BUILD_DIR} -lrta
      deploy:
        provider: releases
        overwrite: true
        file_glob: true
        skip_cleanup: true
        api_key: "${GITHUB_OAUTH_TOKEN}"
        file: "${TRAVIS_BUILD_DIR}/slides/all/target/git-slides-all-*-assemble*"
        #on:
        #  tags: true
