:graphviz: ./src/docs/asciidoc/graphviz
= Git Intro slides

This maven project holds the documentation of the intro git training in form of asciidoc slides,
where the course attendees learn the basics of git like the following.

*What is a Commit, Brach and Tag?*

[graphviz, git-commit-branh-tag, svg]
--
include::./{graphviz}/git-commit-branch-tag.dot[]
--

Attendees will learn to understand that a Commit, Branch or Tag are the same, just an ordianry
hash representing the state of the repository at a commit.

*How does branching works?*

[graphviz, git-branch-model, svg]
--
include::./{graphviz}/git-branch-model.dot[]
--

Attendees will learn how to work with their sources in a git repository properly.
They will learn that feature or hotfix development is performed on different branches, which
have to be merged back into the main branch.

== How to build?
Build the project with the following command.
[source, bash]
----
mvn clean install
----
You will find the html slides in ``target/generated-slides``.

== How to present the slides
Just open one of the generated presentations located in ``target/generated-slides`` in a browser and use the navigation arrows to navigate through the slides.
